"""prmcp.open_pr — open a PR on the configured MCP repo with the synthesized
tool source.

PyGithub 2.x against the repo named in `[mcp] target_repo`. A `dry_run` mode
returns the would-be PR metadata without touching GitHub; the orchestrator
renders that metadata to the console.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Callable, Optional

PR_FOOTER = "\n\n---\nGenerated by prmcp"
AGENT_VALIDATED_LABEL = "agent-validated"


@dataclass(frozen=True)
class PRPreview:
    """Structured result of a dry-run PR call."""
    target: str
    base: str
    branch: str
    file_path: str
    title: str
    body: str

    def __str__(self) -> str:
        return (
            f"[DRY RUN] target={self.target}\n"
            f"[DRY RUN] base={self.base}\n"
            f"[DRY RUN] branch={self.branch}\n"
            f"[DRY RUN] file={self.file_path}\n"
            f"[DRY RUN] title={self.title}\n"
        )


def _utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")


def _branch_name(tool_name: str, *, now: Callable[[], str] = _utc_stamp) -> str:
    return f"prmcp/auto/{tool_name}-{now()}"


def _file_path(tool_dir: str, tool_name: str) -> str:
    return f"{tool_dir.rstrip('/')}/{tool_name}.py"


def _pr_title(tool_name: str) -> str:
    return f"prmcp: add {tool_name} (auto-synthesized)"


def _pr_body(tool_name: str, tool_source: str) -> str:
    return (
        f"prmcp synthesized a new MCP tool `{tool_name}` from a fresh SDK "
        f"resource detected upstream.\n\n"
        f"```python\n{tool_source}\n```"
        f"{PR_FOOTER}"
    )


def open_pr(
    tool_source: str,
    tool_name: str,
    *,
    target: str,
    base: str = "main",
    tool_dir: str = "tools",
    dry_run: bool = False,
    token: Optional[str] = None,
    now: Callable[[], str] = _utc_stamp,
) -> PRPreview | str:
    """Open (or dry-run) a PR adding `tool_source` to `target` as a new file.

    Returns a `PRPreview` if `dry_run`, otherwise the live PR URL string.
    Token defaults to `os.environ["PAT_TOKEN"]` when not provided.
    """
    branch = _branch_name(tool_name, now=now)
    file_path = _file_path(tool_dir, tool_name)
    title = _pr_title(tool_name)
    body = _pr_body(tool_name, tool_source)

    if dry_run:
        return PRPreview(
            target=target,
            base=base,
            branch=branch,
            file_path=file_path,
            title=title,
            body=body,
        )

    if token is None:
        token = os.environ.get("PAT_TOKEN") or ""
    if not token:
        raise RuntimeError(
            "PAT_TOKEN must be set (in .env or the environment) to open a real PR."
        )

    from github import Auth, Github

    gh = Github(auth=Auth.Token(token))
    repo = gh.get_repo(target)

    base_ref = repo.get_git_ref(f"heads/{base}")
    repo.create_git_ref(f"refs/heads/{branch}", base_ref.object.sha)
    repo.create_file(
        path=file_path,
        message=f"prmcp: add {tool_name}",
        content=tool_source,
        branch=branch,
    )
    pr = repo.create_pull(title=title, body=body, head=branch, base=base)
    try:
        pr.add_to_labels(AGENT_VALIDATED_LABEL)
    except Exception:
        pass
    return pr.html_url
